### ISSUE TITLE
[Java]: CWE-601 Spring url redirection detect

### ISSUE THREAD

**Issue by haby0** [github/securitylab#366]
## Query

*Link to pull request with your CodeQL query:*

Relevant PR: https://github.com/github/codeql/pull/5844

## CVE ID(s)

*List the CVE ID(s) associated with this vulnerability. GitHub will automatically link CVE IDs to the [GitHub Advisory Database](https://github.com/advisories).*

## Report

*Describe the vulnerability. Provide any information you think will help GitHub assess the impact your query has on the open source community.*

- [x] Are you planning to discuss this vulnerability submission publicly? (Blog Post, social networks, etc). *We would love to have you spread the word about the good work you are doing*

## Result(s)

*Provide at least one useful result found by your query, on some revision of a real project.*

**Comment by ghsecuritylab** [comment]
Your submission is now in status **SecLab review**.

_For information, the evaluation workflow is the following:
CodeQL initial assessment > SecLab review > CodeQL review > SecLab finalize > Pay > Closed_

**Comment by ghsecuritylab** [comment]
Your submission is now in status **CodeQL review**.

_For information, the evaluation workflow is the following:
CodeQL initial assessment > SecLab review > CodeQL review > SecLab finalize > Pay > Closed_

**Comment by ghsecuritylab** [comment]
Your submission is now in status **SecLab finalize**.

_For information, the evaluation workflow is the following:
CodeQL initial assessment > SecLab review > CodeQL review > SecLab finalize > Pay > Closed_

**Comment by porcupineyhairs** [comment]
This query appears to be a duplicate of my work in github/codeql#4214. The initial draft before merge included all of the sinks along with the flow logic. The result set of the my initial query should cover all of results detected by this one. 

However, per the conversation [here](https://github.com/github/codeql/pull/4214#discussion_r526456656), it was deemed appropriate if the query was split into two separate issues. There is already an open redirect query for Java [here](https://github.com/github/codeql/tree/main/java/ql/src/Security/CWE/CWE-601). The part removed from my initial query is extremely similar to the logic of this query and was to be added to the open redirect query. 

I was planning on taking this up once the query was merged on March 2, I was planning on taking it up. However, due to COVID-19, couldn't make much progress.  Most of the changes in this PR in my opinion can be achieved with simple refactoring of existing code. It would be interesting to see security-lab's stand on this issue.

**Comment by haby0** [comment]
> This query appears to be a duplicate of my work in [github/codeql#4214](https://github.com/github/codeql/pull/4214). The initial draft before merge included all of the sinks along with the flow logic. The result set of the my initial query should cover all of results detected by this one.
> 
> However, per the conversation [here](https://github.com/github/codeql/pull/4214#discussion_r526456656), it was deemed appropriate if the query was split into two separate issues. There is already an open redirect query for Java [here](https://github.com/github/codeql/tree/main/java/ql/src/Security/CWE/CWE-601). The part removed from my initial query is extremely similar to the logic of this query and was to be added to the open redirect query.
> 
> I was planning on taking this up once the query was merged on March 2, I was planning on taking it up. However, due to COVID-19, couldn't make much progress. Most of the changes in this PR in my opinion can be achieved with simple refactoring of existing code. It would be interesting to see security-lab's stand on this issue.

After your comment, I read this PR in full (not followed before), this is your initial [PR] (https://github.com/github/codeql/commit/54b463130831a956554eefc14d494ee344cf06b9).

Here are a few points I want to say: 
- The original intention of the PR you submitted was to detect Spring View operational vulnerabilities, not Spring-specific redirection vulnerabilities.
-  Your initial query did not consider `RedirectView object`/`ModelAndView object`/`"redirect:" prefix` redirection problem.
-  Your initial PR, use the return expression of `SpringControllerMappingMethod` as a sink. I have to admit that the sink here is indeed you Part of the sink. But your sink is too extensive.
- This is the [commit](https://github.com/github/codeql/commit/13c5644803b4be09f2f77aedfe2047104e43f13d) you started to add `"redirect:"`, but it was excluded. The redirection vulnerability is mentioned [here](https://github.com/github/codeql/pull/4214#pullrequestreview-540007331) by @pwntester 


Also, I don't know what this has to do with COVID-19? Please advise.

**Comment by pwntester** [comment]
Hi @porcupineyhairs  @haby0, After reviewing the facts, we don't find reasons to flag this issue as a collision. 
Six months have passed since I identified those cases as View Manipulation FPs and suggested moving them to a specific Open redirect query. We don't expect program participants to read all the PR comments and removed code from all the program submissions to know if someone else may or may not work on a specific query. 
I hope this clears things up, let me know if you have any further questions

**Comment by porcupineyhairs** [comment]
@haby0  What I meant earlier by my comment was most of the changes in this PR can be easily deduced by refactoring existing code. The `ModelAndView`and `SpringControllerMappingMethod` sinks already exist in the code base. As for the "redirect:" prefix, there is already a sanitizer for detecting those. What you do here, is practically an inversion of the sanitizer logic. So that can be easily refactored. Yes, there is a new `RedirectView` sink added but that may be too small a contribution to be eligible for a bounty by itself.

As for, 
> Also, I don't know what this has to do with COVID-19? Please advise.

Never mind, I just meant I got badly infected by corona a few months back and just started working yesterday working hence the delay in follow up. 

But yes, I do agree with @pwntester while the PR was merged two months back,  the comments were made more than six months back. Hence, you deserve the reward for your hard work in his case. Kudos!

**Comment by ghsecuritylab** [comment]
Your submission is now in status **Pay**.

_For information, the evaluation workflow is the following:
CodeQL initial assessment > SecLab review > CodeQL review > SecLab finalize > Pay > Closed_

**Comment by xcorail** [comment]
Created Hackerone report 1204658 for bounty 306369 : [366] [Java]: CWE-601 Spring url redirection detect

**Comment by ghsecuritylab** [comment]
Your submission is now in status **Closed**.

_For information, the evaluation workflow is the following:
CodeQL initial assessment > SecLab review > CodeQL review > SecLab finalize > Pay > Closed_
