### ISSUE TITLE
Java/CWE-036: Calling openStream on URLs created from remote source can lead to file disclosure

### ISSUE THREAD

**Issue by p-** [github/securitylab#41]
## CVE ID(s)

None, but I spotted such a vulnerability in a non-public codebase some years ago.

## Report

If `openStream` is called on a `java.net.URL` that was created from a remote source (query parameters, JSON, etc.)
an attacker can try to pass absolute URLs starting with `file://` or `jar://` to access
local resources in addition to remote ones.

Related pull request:
https://github.com/Semmle/ql/pull/2899

- [x] Are you planning to discuss this vulnerability submission publicly? (Blog Post, social networks, etc). *We would love to have you spread the word about the good work you are doing*

**Comment by xcorail** [comment]
Hey @p- can you please send your email to `securitylab@github.com`?

**Comment by p-** [comment]
@xcorail Done

**Comment by xcorail** [comment]
`Created Hackerone report 844327 for bounty 210658 : [41] Java/CWE-036: Calling openStream on URLs created from remote source can lead to file disclosure`
🎉

**Comment by p-** [comment]
Thank you very much!

**Comment by luchua-bc** [comment]
@p- What do you think about adding a query of calling openConnection() on URLs? It is very similar to the openStream case but openConnection() is more generic since openStream() is actually a shorthand for openConnection().getInputStream(). Invoking these two methods with unsanitized inputs from remote sources could leak to file disclosure or a broader category of CSRF with HTTP/HTTPS requests.

Thanks,
@luchua-bc
