### ISSUE TITLE
[Java]: Add XXE sinks

### ISSUE THREAD

**Issue by haby0** [github/securitylab#420]
## Query

*Link to pull request with your CodeQL query:*

Relevant PR: https://github.com/github/codeql/pull/6453

## CVE ID(s)

*List the CVE ID(s) associated with this vulnerability. GitHub will automatically link CVE IDs to the [GitHub Advisory Database](https://github.com/advisories).*

- CVE-2019-12415（`javax.xml.validation.Validator` used）

## Report

*Describe the vulnerability. Provide any information you think will help GitHub assess the impact your query has on the open source community.*

- [X] Are you planning to discuss this vulnerability submission publicly? (Blog Post, social networks, etc). *We would love to have you spread the word about the good work you are doing*

Yes, I am planning to write a blog post about the query.

## Result(s)

*Provide at least one useful result found by your query, on some revision of a real project.*

- [apache/poi](https://github.com/apache/poi/blob/trunk/poi-ooxml/src/main/java/org/apache/poi/xssf/extractor/XSSFExportToXml.java#L257)

**Comment by kevinbackhouse** [comment]
@haby0: do you have a link to the commit that fixed CVE-2019-12415? Is the link to apache/poi that you included above a different issue?

**Comment by ghsecuritylab** [comment]
Your submission is now in status **Generate Query Results**.

_For information, the evaluation workflow is the following:
SecLab review > Generate Query Results > FP Check > CodeQL review > SecLab finalize > Pay > Closed_

**Comment by ghsecuritylab** [comment]
Your submission is now in status **FP Check**.

_For information, the evaluation workflow is the following:
SecLab review > Generate Query Results > FP Check > CodeQL review > SecLab finalize > Pay > Closed_

**Comment by haby0** [comment]
> @haby0: do you have a link to the commit that fixed CVE-2019-12415? Is the link to apache/poi that you included above a different issue?

Please review.

https://github.com/apache/poi/blob/REL_4_1_0/src/ooxml/java/org/apache/poi/xssf/extractor/XSSFExportToXml.java#L245-L254
https://github.com/apache/poi/blob/REL_4_1_1/src/ooxml/java/org/apache/poi/xssf/extractor/XSSFExportToXml.java#L245-L255

**Comment by kevinbackhouse** [comment]
@haby0: The query doesn't find any results for apache/poi: https://lgtm.com/query/2910840547136075650/
Isn't it supposed to produce a result for [XSSFExportToXml.java, line 257](https://github.com/apache/poi/blob/9f48ce8ba675bf4b9b3ed5b747c4f6f2930b306a/poi-ooxml/src/main/java/org/apache/poi/xssf/extractor/XSSFExportToXml.java#L257)?

**Comment by haby0** [comment]
> @haby0: The query doesn't find any results for apache/poi: https://lgtm.com/query/2910840547136075650/
> Isn't it supposed to produce a result for [XSSFExportToXml.java, line 257](https://github.com/apache/poi/blob/9f48ce8ba675bf4b9b3ed5b747c4f6f2930b306a/poi-ooxml/src/main/java/org/apache/poi/xssf/extractor/XSSFExportToXml.java#L257)?

@kevinbackhouse  I did not specifically model this CVE. 

The parsed xml data is assigned to the map class variable through the constructor [Create instance assignment](https://github.com/apache/poi/blob/0614835c55f44ab6f3e9b0850ca51e0e53a65a49/poi-ooxml/src/main/java/org/apache/poi/xssf/extractor/XSSFExportToXml.java#L99), the isValid method parses [map](https://github.com/apache/poi/blob/0614835c55f44ab6f3e9b0850ca51e0e53a65a49/poi-ooxml/src/main/java/org/apache/poi/xssf/extractor/XSSFExportToXml.java#L128) variable data.

https://lgtm.com/query/6966805035403506339/

**Comment by haby0** [comment]
@kevinbackhouse Hello, I don't know if my reply solves your question?

**Comment by kevinbackhouse** [comment]
@haby0: sorry for not responding yesterday. I have spent some time investigating this and I am struggling to understand how it meets the [CVE requirement](https://securitylab.github.com/bounties/). ("To be considered, your query must find at least one CVE that was not previously found by an existing query ...") You are using CVE-2019-12415, but as far as I can tell, this query doesn't detect CVE-2019-12415. I have been attempting to verify your claim by running the query on version REL_4_1_1, but I just realized that it isn't even necessary to do that, because they haven't merged the fix into their `trunk` branch. Here's a link to the latest version of `XSSFExportToXml.java` on the `trunk` branch: [link](https://github.com/apache/poi/blob/9f48ce8ba675bf4b9b3ed5b747c4f6f2930b306a/poi-ooxml/src/main/java/org/apache/poi/xssf/extractor/XSSFExportToXml.java#L252). It doesn't include the call to `trySetFeature(factory, XMLConstants.FEATURE_SECURE_PROCESSING, true)`. When you run a query on LGTM, it runs it on the latest `trunk` branch, so your query ought to produce a result for that function.

**Comment by haby0** [comment]
@kevinbackhouse [apache/poi](https://github.com/apache/poi): A Java library for reading and writing Microsoft Office binary and OOXML file formats. no remote user input.

In addition, the SchemaFactory instance created by [link](https://github.com/apache/poi/blob/9f48ce8ba675bf4b9b3ed5b747c4f6f2930b306a/poi/src/main/java/org/apache/poi/util/XMLHelper.java#L240-L245) It is safe.

**Comment by kevinbackhouse** [comment]
@haby0: I have created a [clone](https://github.com/kevinbackhouse/test-poi) of apache/poi with the vulnerability deliberately [inserted](https://github.com/kevinbackhouse/test-poi/commit/8f1a278fd300c4b0b9cc1118aaf5c5f631b3301e). For some reason, LGTM's query console won't let me query the project, so I had to test your query offline. I built a database for commit [`bea6ae1`](https://github.com/kevinbackhouse/test-poi/tree/bea6ae129adb516a992a64517834d7cf2f27c978) like this:

```bash
codeql database create --language=java poi-bea6ae129adb516a992a64517834d7cf2f27c978
```

When I run your query on that database, I do not get any results. Therefore, I do not believe that this query is able to catch CVE-2019-12415, so I am afraid I have to reject this bounty submission because it does not meet the CVE requirement.

**Comment by ghsecuritylab** [comment]
Your submission is now in status **Closed**.

_For information, the evaluation workflow is the following:
SecLab review > Generate Query Results > FP Check > CodeQL review > SecLab finalize > Pay > Closed_

**Comment by haby0** [comment]
> > `@haby0`: I have created a [clone](https://github.com/kevinbackhouse/test-poi) of apache/poi with the vulnerability deliberately [inserted](https://github.com/kevinbackhouse/test-poi/commit/8f1a278fd300c4b0b9cc1118aaf5c5f631b3301e). For some reason, LGTM's query console won't let me query the project, so I had to test your query offline.
> 
> Works for me:
> https://lgtm.com/query/4891641574424382455/

Updated result.

**Comment by kevinbackhouse** [comment]
@haby0: please could you open a new issue? (To restart our automation.)
I notice that [jenkinsci/rundeck-plugin](https://github.com/jenkinsci/rundeck-plugin) is a fork, so LGTM cannot analyze it. Have you run your query offline to check that it is able to detect CVE-2020-2144?

**Comment by haby0** [comment]
> @haby0: please could you open a new issue? (To restart our automation.)
> I notice that [jenkinsci/rundeck-plugin](https://github.com/jenkinsci/rundeck-plugin) is a fork, so LGTM cannot analyze it. Have you run your query offline to check that it is able to detect CVE-2020-2144?

Yes. Jenkinsci/rundeck-plugin cannot build the database on lgtm, I run it locally.
