### ISSUE TITLE
Add check for disabled HTTPOnly setting in Tomcat

### ISSUE THREAD

**Issue by Mithrilwoodrat** [github/securitylab#45]
## CVE ID(s)

There's no CVE for this.

## Report

Tomcat beyond vesion 6 has enable HTTPOnly for JSESSIONID by default. But, it's possible to disable it, which allowed an attacker get another user's sessionid by Cross-Site Scripting(XSS) attack,

[CWE-1004: Sensitive Cookie Without 'HttpOnly' ]Flag(https://cwe.mitre.org/data/definitions/1004.html)

Tomcat HTTPOnly can be disabled via web.xml configuration by add config below

<context-param>
        <param-name>useHttpOnly</param-name>
        <param-value>false</param-value>
</context-param>

I created a CodeQL check ([Semmle/ql]#2912(https://github.com/Semmle/ql/pull/2912))  which finds all Tomcat's web.xml set useHttpOnly to false

- [ ] Are you planning to discuss this vulnerability submission publicly? (Blog Post, social networks, etc). *We would love to have you spread the word about the good work you are doing*

**Comment by xcorail** [comment]
Hi @Mithrilwoodrat,

Thanks for the submission! We have reviewed your report and validated your findings. After internally assessing the findings and the query we have determined this query does not meet our minimum complexity requirement and is not eligible for a reward under the Bug Bounty program. We only award higher quality queries as part of the program with attribution on our Bug Bounty site and a payout between $500 and $3,000.

Even though this issue was assessed as being ineligible, we appreciate you bringing it to our attention. It has been merged as part of the experimental queries, and would still like to offer you $250.

Best regards and happy hacking!

`Created Hackerone report 888666 for bounty 220375 : [45] Add check for disabled HTTPOnly setting in Tomcat`

**Comment by ranasarangi** [comment]
<script>alert(document.domain);</script>

**Comment by ranasarangi** [comment]
`alert("1");`

**Comment by ranasarangi** [comment]
uuu

**Comment by ranasarangi** [comment]
>'>"><img src=x onerror=alert(0)>.

**Comment by ranasarangi** [comment]
>'>"><img src=x onerror=alert(0)>.

**Comment by ranasarangi** [comment]
>'>"><img src=x onerror=alert(0)>.

**Comment by ranasarangi** [comment]
>'>"><img src=x onerror=alert("0");><img>

**Comment by ranasarangi** [comment]
>'>"><link src=x onerror=alert(0)>hi</link>

**Comment by ranasarangi** [comment]
>'>"><img src=x onerror=alert(document.domain);></img>

**Comment by ranasarangi** [comment]
>'>"><a href="https://www.google.com">Hi</a>

**Comment by ranasarangi** [comment]
>'>"><a href="https://www.google.com">Clickme</a>

**Comment by ranasarangi** [comment]
>'>"><a href="https://www.google.com">clickme</a>

**Comment by intrigus-lgtm** [comment]
@ranasarangi please stop spamming.

**Comment by ranasarangi** [comment]
>'>"><body bgcolor="black"></body>
