### ISSUE TITLE
[Python]: CWE-073 Arbitrary file reading

### ISSUE THREAD

**Issue by haby0** [github/securitylab#463]
## Query

*Link to pull request with your CodeQL query:*

Relevant PR: https://github.com/github/codeql/pull/6977

## CVE ID(s)

*List the CVE ID(s) associated with this vulnerability. GitHub will automatically link CVE IDs to the [GitHub Advisory Database](https://github.com/advisories).*

- [CVE-2021-41185](https://github.com/kizniche/Mycodo/security/advisories/GHSA-252r-94ph-m229)

## Report

*Describe the vulnerability. Provide any information you think will help GitHub assess the impact your query has on the open source community.*

- [x] Are you planning to discuss this vulnerability submission publicly? (Blog Post, social networks, etc). *We would love to have you spread the word about the good work you are doing*

## Result(s)

*Provide at least one useful result found by your query, on some revision of a real project.*

- [CVE-2021-41185](https://github.com/kizniche/Mycodo/security/advisories/GHSA-252r-94ph-m229)

**Comment by haby0** [comment]
> @pwntester @haby0 I missed [this](https://github.com/github/codeql/pull/6977/files#diff-8b08a136e9cfca3a648e75cd69ebe5ebd15b9911381e3b0ac8fb5a73354b8255R78) in my comments earlier.
> 
> This 2 word change adds a new source which leads to detection of a CVE.
> 
> All of this PR may not be a duplicate after all.

I need to clarify, here should be the CVE that I wrote the detection rules first and applied for later.

**Comment by m-y-mo** [comment]
@haby0
This seems to be a slight variation of the submission that was [rejected in the past](https://github.com/github/securitylab/issues/463) The reason for the rejection of that query is that, while the query adds refinement to the standard query that would otherwise have flagged up all file manipulation operations with untrusted file path, we believe that such refinements does not contribute to the balancing of FP vs FN that we'd like to have in our queries. Since the main differences between this query and the rejected one is that it now also flags file delete operations, which is still only a refinement to the standard query that does not contribute to balancing of FP vs FN. (In fact, it'll probably overlap even more with the standard query because read + delete is a larger subset of all file manipulations than just read) As such, we decide to reject this query based on the same reason.
In the future, please do not reach out to members of the security lab privately regarding submission details. Such communications will not be responded. If there is a need to communicate privately, then the only channel that should be used is the contact details provided in the [bounty guidelines page](https://securitylab.github.com/bounties/) and only for the legitimate purposes set out in the guidelines. 
Your current submission may be more suitable for the Bug Slayer program. I'd encourage you to take a look at the details and consider submitting it to the Bug Slayer program.
Thank you very much for your submission.
