### ISSUE TITLE
[Python]: Arbitrary file read and delete

### ISSUE THREAD

**Issue by haby0** [github/securitylab#496]
## Query

*Link to pull request with your CodeQL query:*

Relevant PR: https://github.com/github/codeql/pull/7293

Modified since [#6977](https://github.com/github/codeql/6977).

## CVE ID(s)

*List the CVE ID(s) associated with this vulnerability. GitHub will automatically link CVE IDs to the [GitHub Advisory Database](https://github.com/advisories).*

- CVE-2021-41185
- CVE-2021-43775

## Report

*Describe the vulnerability. Provide any information you think will help GitHub assess the impact your query has on the open source community.*

- [x] Are you planning to discuss this vulnerability submission publicly? (Blog Post, social networks, etc). *We would love to have you spread the word about the good work you are doing*

## Result(s)

*Provide at least one useful result found by your query, on some revision of a real project.*

- CVE-2021-41185
- CVE-2021-43775

**Comment by m-y-mo** [comment]
@haby0
This seems to be a slight variation of the submission that was rejected in the past The reason for the rejection of that query is that, while the query adds refinement to the standard query that would otherwise have flagged up all file manipulation operations with untrusted file path, we believe that such refinements does not contribute to the balancing of FP vs FN that we'd like to have in our queries. Since the main differences between this query and the rejected one is that it now also flags file delete operations, which is still only a refinement to the standard query that does not contribute to balancing of FP vs FN. (In fact, it'll probably overlap even more with the standard query because read + delete is a larger subset of all file manipulations than just read) As such, we decide to reject this query based on the same reason.
In the future, please do not reach out to members of the security lab privately regarding submission details. Such communications will not be responded. If there is a need to communicate privately, then the only channel that should be used is the contact details provided in the bounty guidelines page and only for the legitimate purposes set out in the guidelines.
Your current submission may be more suitable for the Bug Slayer program. I'd encourage you to take a look at the details and consider submitting it to the Bug Slayer program.
Thank you very much for your submission.

**Comment by haby0** [comment]
closed.

**Comment by haby0** [comment]
> @haby0 This seems to be a slight variation of the submission that was rejected in the past The reason for the rejection of that query is that, while the query adds refinement to the standard query that would otherwise have flagged up all file manipulation operations with untrusted file path, we believe that such refinements does not contribute to the balancing of FP vs FN that we'd like to have in our queries. Since the main differences between this query and the rejected one is that it now also flags file delete operations, which is still only a refinement to the standard query that does not contribute to balancing of FP vs FN. (In fact, it'll probably overlap even more with the standard query because read + delete is a larger subset of all file manipulations than just read) As such, we decide to reject this query based on the same reason. In the future, please do not reach out to members of the security lab privately regarding submission details. Such communications will not be responded. If there is a need to communicate privately, then the only channel that should be used is the contact details provided in the bounty guidelines page and only for the legitimate purposes set out in the guidelines. Your current submission may be more suitable for the Bug Slayer program. I'd encourage you to take a look at the details and consider submitting it to the Bug Slayer program. Thank you very much for your submission.

I saw your message yesterday and didn't reply in time. Sorry.

First of all, thank you for your reply. @pwntester is the review of this query. There are some undisclosed vulnerability information in the information I submitted, so I directly sent it to him. In addition, the email is also your work email.

Based on @pwntester's reply (https://github.com/github/securitylab/issues/463#issuecomment-954515915), I understand that there is no problem resubmitting this query.

 CVE-2021-43775: I got this CVE from LGTM using this query, please pay attention to the date (https://github.com/aimhubio/aim/issues/999). After the CVE is made public, https://github.com/github/codeql/pull/7228 This PR improves FastAPI modeling.

**Comment by pwntester** [comment]
> @pwntester is the review of this query. There are some undisclosed vulnerability information in the information I submitted, so I directly sent it to him. 

No, Im not, I passed your email to the researcher on duty this week (@m-y-mo) along with the previous submission details so he could catch up and triage this new submission.

> Based on @pwntester's reply (#463 (comment)), I understand that there is no problem resubmitting this query.

I refer to new queries such as the MyBatis one. Submitting a query again without modifying the underlying reason why it was rejected in the first place, will get the new submission rejected again.

**Comment by haby0** [comment]
> No, Im not, I passed your email to the researcher on duty this week (@m-y-mo) along with the previous submission details so he could catch up and triage this new submission.

You are the reviewer of (https://github.com/github/securitylab/issues/463#issuecomment-954515915), so I sent the information to your email.

> I refer to new queries such as the MyBatis one. Submitting a query again without modifying the underlying reason why it was rejected in the first place, will get the new submission rejected again.

> In addition, it may be possible that the file is returned in a different way such as dumping their contents in a web view, out of band, etc and those cases would be missed by your query.

> We would like to encourage you to keep submitting your great queries!

1. In the latest PR, I modeled the views of Django, FastApi, Flask, Stdlib, and Tornado; 2. The FileResponse of the FastApi framework is also a sink; 3. I added some sinks for file deletion.

**Comment by haby0** [comment]
@m-y-mo hi, friend. I sent you a supplementary email (I'm sure that the information in the supplementary email should not be displayed here). Is there any news synchronized for me?
