### ISSUE TITLE
[CPP]: Add query for CWE-476: NULL Pointer Dereference when using exception handling blocks 

### ISSUE THREAD

**Issue by ihsinme** [github/securitylab#671]
### Query PR

https://github.com/github/codeql/pull/8245

### Language

C/C++

### CVE(s) ID list

[CVE-2020-15304](https://nvd.nist.gov/vuln/detail/CVE-2020-15304)

### CWE

CWE-476: NULL Pointer Dereference

### Report

1. The vulnerability is that exception handling may start before the end of memory allocation.
2. It is possible to access an unallocated memory area, or an attempt to free unallocated memory
3. The request handles various situations, memory allocation after a possible exception.
4. The main means of eliminating false positives is the control of zero initialization.

### Are you planning to discuss this vulnerability submission publicly? (Blog Post, social networks, etc).

- [X] Yes
- [ ] No

### Blog post link

https://twitter.com/ihsinme/status/1522510143421915138

**Comment by m-y-mo** [comment]
Thank you very much for your submission. Unfortunately, after looking at the impact and scope of the query, we decided that we are unable to accept the submission due to both the impact and scope being rather low. The reason for this is that, the query catches a case where variables are allocated inside a try block and deleted in catch block. If the variable is initialized outside the block, then the worst outcome would normally be a null pointer dereference, which is a minor security issue and in some context, it isn't considered a security issue (e.g. many client side applications). If the variable is not initialized at all, then it could become a security issue, but in that case, the problem can be handled more effectively with basic compiler checks. As the query is also looking at a very special scenario, the scope of the query is also very narrow. As such, we decided that the query does not meet our entry criteria due to both the scope and impact being low.

**Comment by ihsinme** [comment]
good afternoon @m-y-mo 
Thanks for the prompt and clear answer.
For my part, I would like to make a few comments.
1. in cve dereferencing is medium, not low.
2. This query considers 3 different situations. two positions clearing the unselected element. and one dereference. in my opinion, all these problems are important and are present in real code.
3. if you are talking about insufficient cleaning of false positives, I would like to take a look at them and clean them up.
4. if you are talking about the level of threat, then I don’t understand the assessment a bit, the presence of cve indicates a threat.
5. if about a small amount of detection, then in PR I presented several detections, and I expect more, I would like to know the amount that is needed.

Please look again at my request.
thank.

**Comment by m-y-mo** [comment]
Thanks for the reply. The decision is based on:
1. Although the CVE reference state as medium, for our purpose, we still consider it as a low-medium impact query. The query impact does not map directly to CVE rating, and certainly not we also consider the general context. In this case, the issue is in the low end of medium for the applications where it is a problem, and for applications where they are not a problem, it is not a security issue, so the impact is judged as low/medium low.
2. Although you have 3 different situations, they are all subcases of allocation/initialization inside a try block and then using (dereference/clear) it inside a catch block, so the overall scope is still small because the parent scenario (allocation in try and use in catch) is still a rather narrow case. So yes, they do exist in real code, but it is still a rather special issue.
We sometimes make exceptions to accept queries that are either of low impact or small scope, but in this case, I'm afraid the query does not meet the requirements in both areas and hence the decision to reject it. Thanks.

**Comment by ihsinme** [comment]
@m-y-mo 
I understand .
but.
1. A low threat level in your program does not result in a rejection on your part, you just reward a low bar.
2. Low discovery rate, please check if there are a few projects I need to find before applying for a reward. if these are reasonable numbers, I hope to reach them.

please understand me correctly, I understand that you can make any decision, it is your right. but I want to understand the nature of your assessments in order to reduce the number of rejections on your part.

Thank you for your time.

**Comment by ihsinme** [comment]
addition.
I looked at the request again, the third occurrence is quite frequent. this happens when trying to allocate memory in a try block and clean up in a catch block. and the exception is not taken into account when allocated.

this approach is very common.

**Comment by ihsinme** [comment]
thanks again for the clarification.
although it seems to me that your statements are quite subjective, at least I did not find them in the rules. except for situations about a very simple request, this is not my case.

1. You are talking about the situation with zero initialization for the second time, but the request should skip them.
2. a good example about the requirements of the compiler, but if we are talking about placing a pointer inside the structure, then the compiler will not swear, and the allocation of the structure will fill the fields with random data. and the compiler's requirement is a stylistic requirement, not a security requirement.
3. I also disagree about the FP, if there are examples, I will correct it.

Thank you very much for answering my questions, even if it doesn't change your mind.

**Comment by ihsinme** [comment]
addition.
As far as improvements in codeql , you didn't detect this cve and now you find it, it's a sign of improvement. which is specified in the rules.

**Comment by xcorail** [comment]
Hello @ihsinme 

As per our rules when a hunter challenges the decision, Mo has consulted other members of the research team and the CodeQL team, and the consensus is that 
1. this query does not meet the standards to be included in our standard security queries, 
2. this query would need a significant rewrite from our CodeQL team

Therefore we will reject the submission.
However, the team also recognized that it's a non-trivial query, that finds a CVE, and they decided to offer you a $250 reward in appreciation of the work you put into this submission.

Best regards

**Comment by ghsecuritylab** [comment]
Your submission is now in status **Final decision**.

_For information, the evaluation workflow is the following:
Initial triage > Test run > Results analysis > Query review > Final decision > Pay > Closed_

**Comment by ghsecuritylab** [comment]
Your submission is now in status **Closed**.

_For information, the evaluation workflow is the following:
Initial triage > Test run > Results analysis > Query review > Final decision > Pay > Closed_

**Comment by ihsinme** [comment]
thanks
