### ISSUE TITLE
[CPP]: Add query for CWE-670: Always-Incorrect Control Flow Implementation when use SSL_shutdown

### ISSUE THREAD

**Issue by ihsinme** [github/securitylab#676]
### Query PR

https://github.com/github/codeql/pull/9087

### Language

C/C++

### CVE(s) ID list

[CVE-2008-1531](https://github.com/advisories/GHSA-2p48-prhc-qmgx)

### CWE

CWE-670: Always-Incorrect Control Flow Implementation

### Report

1. When closing connections, situations of unequal state for two participants are possible. this can be used to re-establish connections.
2. Reconnection by a third party.
3. I'm looking for an unhandled call to re-close the connection.
4. According to the documentation, close calls must be processed, so the search for unhandled calls is a good defense against FP

### Are you planning to discuss this vulnerability submission publicly? (Blog Post, social networks, etc).

- [X] Yes
- [ ] No

### Blog post link

https://twitter.com/ihsinme/status/1526809699231969281

**Comment by agustingianni** [comment]
Hi @ihsinme,

Thanks for the submission! We have reviewed your report and validated your findings. After internally assessing the findings and the query we have determined this query does not have a high impact and therefore not eligible for a reward under the Bug Bounty program.

Even though this issue was assessed as being ineligible, we appreciate you bringing it to our attention.

Best regards and happy hacking!

**Comment by ihsinme** [comment]
@agustingianni i respect your decision.

However, it would be great to have objective indicators, as far as I understand, having cve and detection in real projects is no longer enough?

**Comment by ihsinme** [comment]
Perhaps I need to apologize for not being detailed enough.(

**Comment by ghsecuritylab** [comment]
Your submission is now in status **Closed**.

_For information, the evaluation workflow is the following:
Initial triage > Test run > Results analysis > Query review > Final decision > Pay > Closed_
