### ISSUE TITLE
[CPP]: Add query for CWE-758: Reliance on Implementation-Defined Behavior when using malloc with zero size

### ISSUE THREAD

**Issue by ihsinme** [github/securitylab#689]
### Query PR

https://github.com/github/codeql/pull/9088

### Language

C/C++

### CVE(s) ID list

- [CVE-2017-6886](https://nvd.nist.gov/vuln/detail/CVE-2017-6886)
- [CVE-2013-6378](https://nvd.nist.gov/vuln/detail/CVE-2013-6378)

### CWE

CWE-758: Reliance on Implementation-Defined Behavior

### Report

1. Errors when allocating memory of size zero
2. The operation of the function when issuing a memory block of zero size is not defined, therefore, if the size is not checked before allocation, then it is impossible to judge by the pointer whether the memory was allocated or not.
3. The strategy is based on the absence of a size check, getting the size from a file or the ability to return zero, access to the allocated memory.
4. the request is maximally narrowed for these conditions

### Are you planning to discuss this vulnerability submission publicly? (Blog Post, social networks, etc).

- [X] Yes
- [ ] No

### Blog post link

https://twitter.com/ihsinme/status/1534890236366528513

**Comment by jorgectf** [comment]
👋 @ihsinme 

Apologies for the delay 🙇, and thank you so much for writing [this explanation](https://github.com/github/codeql/pull/9088#issuecomment-1164247541)!

Since the main problem is providing `malloc(0)` but your query takes a step further checking where the pointer flows to; are you planning to extend these cases? (In case there are more and they are interesting for you).

**Comment by jorgectf** [comment]
@ihsinme

I don't have enough experience in c/cpp to provide new situations for this query. I just wanted to check if you had in mind adding more checks to this query. If you don't, then we can continue the process with the query as is.

**Comment by jorgectf** [comment]
👋 @ihsinme 

Unfortunately, with regards to the test run, your query only had one hit ([this FP](https://lgtm.com/projects/g/xrootd/xrootd/snapshot/4d97a80aa2fb81fb5bb020995d628ecb587e529e/files/src/XrdOuc/XrdOucGatherConf.cc?sort=name&dir=ASC&mode=heatmap#x745681e9d7cc7739:1)). Is there any chance you could improve the query? For instance, by using "more high-level libraries" as `@MathiasVP` suggested [in the PR review](https://github.com/github/codeql/pull/9088#pullrequestreview-981682273), going for the pure error (finding `malloc(0)`) instead of also checking *the afterwards* (just in case that is the reason why there are almost no results), or extending the request ([as you thought](https://github.com/github/securitylab/issues/689#issuecomment-1175908066)). Otherwise, this submission will not be accepted.

Let me know your thoughts,
Jorge.

**Comment by ihsinme** [comment]
Good afternoon @jorgectf.
Thanks for the answer.
1. your FP is interesting, I will definitely figure out why it happened and fix it.
2. The detection is really small, in my tests I observed only two.
https://github.com/akjmicro/dclang/blob/master/string_ops.c#L190
https://github.com/gibalou/containers/blob/0407752bf278a5f0a5a13205f4b3f221f36a4f9f/test/datagram_sender.c#L55
4. I will fix the request  by using "more high-level libraries" 
5. I have some ideas on how to expand the query, I'll add them and get back to you.

**Comment by ihsinme** [comment]
continuation of the conversation https://github.com/github/codeql/pull/9088#issuecomment-1273634926.

`about fair play`
when sending a request, I never know which collections it will be evaluated on and how many results in which projects should be in order to pass the bar. I checked my collection before submitting and found 2 detections for 17 and 1 star projects and was hoping your collection would meet the bare minimum. when I found out that your collection did not have detection, I suggested extension options under CWE-758. I didn't think I was being dishonest, I wanted to make the best request and at all stages I discussed the steps with you.

`regarding the name`
if this is a really important question, then I am ready to close this request and open a new one with a different name or correct the name of this application.
at the same time, if you select not the last 4 words in the title, but the first 5, you get the correct title)

`relatively higher rewards`
Unfortunately, I have no experience in finding and getting CVE and expect difficulties in this matter, so all my requests use an already existing CVE.

`about my decision`
I have already pointed out several times that I don’t really understand what is happening, a month ago the development of the request suited everyone and everything went towards increasing detection at least to the minimum level. and here @MathiasVP 
 says that he is waiting for the result of the execution of command SecLab, and if they are bad, then he will think about whether to merge, and a member of team SecLab @jorgectf, referring to @MathiasVP, says that perhaps there is no need to merge.

my solution is simpler, I still think that the request in its current form covers important bugs in the code (CWE-758) that are currently not found and may be useful, so it should be merged in the CodeQL regardless of the reward decision, at least in the form of a set of test cases for the following implementations (if the request code is really fatally bad and cannot be improved by my efforts).
As for the minimum bar I'm aiming for, I'm waiting for the results of scanning your collection.

**Comment by jorgectf** [comment]
👋 @ihsinme 

Although we think the __initial__ idea of the query was good, our rules state that `Queries must meet at least the requirements for experimental queries`, and your query, __in this current state__, cannot be merged. Therefore I'm closing this issue.

**Comment by ghsecuritylab** [comment]
Your submission is now in status **Closed**.

_For information, the evaluation workflow is the following:
Initial triage > Test run > Results analysis > Query review > Final decision > Pay > Closed_
