### ISSUE TITLE
[Python] Unsafe unpacking using `shutil.unpack_archive()` query and tests

### ISSUE THREAD

**Issue by Sim4n6** [github/securitylab#719]
### Query PR

https://github.com/github/codeql/pull/11570

### Language

Python

### CVE(s) ID list

- CVE-2022-23522
- CVE-2022-23530
- More to come soon.

### CWE

CWE-022

### Report

1. Unsafe unpacking of a tarball retrieved from a remote location.
2. A remotely downloaded tarball may be malicious and contains filename paths with relative path `..` or absolute paths starting with `/`. It seems that `shutil.unpack_archive()` does unpack tarballs with extensions `.tar`, `.tar.gz`, `.tar.xz`, `.tar.bz2`, or `.gztar` in an unsafe way. Which leads to the extraction of files within the tarball to an unintended folder.
3. I use a simple fact: 
 - Source: remote HTTP client request.
 - Sink a call to `shutil.unpack_archive()`.
 - additional taint steps: opening and writing the response to a tarball.
4. Well, I removed a couple of in the python standard library cases. 
5. This CodeQL query is very specific but since the `shutil.unpack_archive()` is unsafe, it could be extended to more sources. Here, I considered a remotely retrieved tarball, but in fact, any tarball input could be identified as malicious. For instance, a CLI tool that takes a path to a tarball in the filesystem is not yet identified with this CodeQL query.

### Are you planning to discuss this vulnerability submission publicly? (Blog Post, social networks, etc).

- [ ] Yes
- [x] No

### Blog post link

https://www.getrevue.co/profile/sim4n6

**Comment by Sim4n6** [comment]
CVE-2022-23522 got assigned and more to come. I have also added other *sources* such as  filename path from a CLI argument.

**Comment by pwntester** [comment]
Hi @Sim4n6, thanks for yet another submission! 

Sorry this one is taking so long but there was an ongoing inter-team discussion and, because of the different xmas breaks, it took longer to have everyone onboard. The query, as it is now, does not meet the minimum scope criteria to make it eligible for a bounty. We have been discussing different possibilities such as combining with other existing queries or making it a semantic query. While looking into the sink, @JarLob spotted that there are other similar and also vulnerable sinks (eg: [tarfile](https://docs.python.org/3/library/tarfile.html#tarfile.TarFile.extractall) and [zipfile](https://docs.python.org/3/library/zipfile.html#zipfile.ZipFile.extractall)) that could be added to this query so increase its scope. Adding support for these additional sinks would increase the scope score and make it eligible. Would you willing to do so?

**Comment by Sim4n6** [comment]
Sure why not, but one detail please tarslip and zipslip queries are already available in the experimental queries do you suggest that I update them accordingly to consider the shutil.unpack sink? 😃

**Comment by pwntester** [comment]
Yep, I think it would make sense to integrate this one into the tarslip one by creating a new source that includes [all the cases you considered](https://github.com/github/codeql/blob/main/python/ql/src/experimental/Security/CWE-022bis/TarSlipImprov.ql#L59). So the new source would be either the creation of a new TarFile or a path coming from the sources you collected.

The problem here is that your source may be incomplete and therefore we may not report some issues. We could just report all calls to `unpack_archive()` but such simple semantic query would not meet the acceptance criteria. We think that there is value in the source and taintsteps you wrote and therefore will accept it as an extension of the existing tarslip query

**Comment by Sim4n6** [comment]
Perfect, I will be working on that

**Comment by pwntester** [comment]
Hi @Sim4n6 we have decided to accept the query as is since merging it with the existing one would be mixing sources and sinks that were not really meant to work together. There is nothing for you to do. Thanks for the contribution!

**Comment by Sim4n6** [comment]
Great thank you @pwntester I was going crazy with that... By the way, I have identified at least 03 CVEs with the query.

**Comment by ghsecuritylab** [comment]
Your submission is now in status **Test run**.

_For information, the evaluation workflow is the following:
Initial triage > Test run > Results analysis > Query review > Final decision > Pay > Closed_

**Comment by Sim4n6** [comment]
Hi @pwntester, 

I'm getting more potential CVEs assigned with the modified version of the query, and I would like to consider the sinks and the sources (as additional steps) from the [TarSlip](https://github.com/github/codeql/blob/7271d9987e54dcff8f1d9461f5f7f48376dd4915/python/ql/src/experimental/Security/CWE-022bis/TarSlipImprov.ql) into the [UnsafeUnpack query](https://github.com/github/codeql/pull/11570). It would look to me much more as modeling a whole and a viable attack from a RemoteFlowSource to an unsafe extraction. May the new query be considered for a higher bounty in that case, please?  or do you suggest that I constrain the UnpackUnsafe for the sink `shutil.unpack_archive()` and apply for the bug slayer program, next? 

Please, how do you suggest that I proceed?

**Comment by pwntester** [comment]
Hi @Sim4n6,

That would increase the Scope of the query for sure. However, the scope is not the only element considered for the bounty level so I cant assure you that a higher scope level will transform into a higher bounty level. I encourage you to do so and at the same time, submit for the Bug Slayer program if you meet the criteria

**Comment by Sim4n6** [comment]
No problem, I will add the TarSlip sinks&sources to the UnsafeUnpack query. And latter apply for the Bug slayer. Thanks

**Comment by ghsecuritylab** [comment]
Your submission is now in status **Query review**.

_For information, the evaluation workflow is the following:
Initial triage > Test run > Results analysis > Query review > Final decision > Pay > Closed_

**Comment by ghsecuritylab** [comment]
Your submission is now in status **Final decision**.

_For information, the evaluation workflow is the following:
Initial triage > Test run > Results analysis > Query review > Final decision > Pay > Closed_

**Comment by Sim4n6** [comment]
So what is the final ruling on the matter, please?

**Comment by ghsecuritylab** [comment]
Your submission is now in status **Pay**.

_For information, the evaluation workflow is the following:
Initial triage > Test run > Results analysis > Query review > Final decision > Pay > Closed_

**Comment by xcorail** [comment]
Created Hackerone report 1898441 for bounty 463052 : [719] [Python] Unsafe unpacking using shutil.unpack_archive() query and tests

**Comment by ghsecuritylab** [comment]
Your submission is now in status **Closed**.

_For information, the evaluation workflow is the following:
Initial triage > Test run > Results analysis > Query review > Final decision > Pay > Closed_
