### ISSUE TITLE
[Go]: New File System Access Sinks

### ISSUE THREAD

**Issue by amammad** [github/securitylab#782]
### Query PR

https://github.com/github/codeql/pull/14064

### Language

GoLang

### CVE(s) ID list

- https://github.com/advisories/GHSA-hf7j-xj3w-87g4
- https://github.com/advisories/GHSA-85cf-gj29-f555 with [this fix commit](https://github.com/1Panel-dev/1Panel/commit/f6b84d384e41c1c708d41160b2af9761d984f558#diff-3daefeffef5edafe17bc47b7e75c1332b684aa728ee67efffc6fe795d95d3627L556-L568)

### CWE

CWE-022

### Report

File System Access Sinks can are really valuable and can be used in multiple places to write security queries specially for writing Path Traversal detection queries.
I've added multiple New File System Access Sinks, 

### Are you planning to discuss this vulnerability submission publicly? (Blog Post, social networks, etc).

- [X] Yes
- [ ] No

**Comment by sylwia-budzynska** [comment]
Hello @amammad 
After having a look at your submission, we realized there might be room for a future bug bounty submission, if you'd be interested.

Your submission adds fasthttp sinks. The fasthttp library is not modeled in CodeQL and if you'd like to, you could create a bug bounty submission modeling the whole library in CodeQL.

Let us know what you think and if you'd like to pursue this idea.

**Comment by sylwia-budzynska** [comment]
@amammad :wave: I’m the one taking care of this submission, so I will answer.

We have a number of scores that we rate all submissions on. Adding more and new sources could increase the scope metric in this submission.

Your submission adds golang sinks for eight frameworks and libraries. It already has a very wide scope, so there’s no need to add more sources to it. Besides, these sources are already a part of your other submission with the DOS queries and so they cannot be a part of two submissions at the same time. All in all, this is already a very good submission in regards of scope. Looking forward to see more great submissions like these :+1:

If you’d like to maximize payout for your future submissions, here are a few general guidelines, that we might take into consideration when reviewing a submission.

- the submission models widely-used frameworks/libraries
- the vulnerability modeled in the submission is impactful
- the submission finds new true positive vulnerabilities
- the submission finds very few false positives
- code in the submission is easy to read and will be easy to maintain
- documentation is written clearly, highlighting the impact of the issue it finds and is written without grammatical or other errors. The code samples clearly show the vulnerability
- the submission includes tests, change note etc.

Please note that these are guidelines, not rules. Since we have a lot of different types of submissions, the guidelines might vary for each submission.

Happy hacking!

**Comment by ghsecuritylab** [comment]
Your submission is now in status **Final decision**.

_For information, the evaluation workflow is the following:
Initial triage > Test run > Results analysis > Query review > Final decision > Pay > Closed_

**Comment by ghsecuritylab** [comment]
Your submission is now in status **Pay**.

_For information, the evaluation workflow is the following:
Initial triage > Test run > Results analysis > Query review > Final decision > Pay > Closed_

**Comment by xcorail** [comment]
Created Hackerone report 2206657 for bounty 520801 : [782] [Go]: New File System Access Sinks

**Comment by ghsecuritylab** [comment]
Your submission is now in status **Closed**.

_For information, the evaluation workflow is the following:
Initial triage > Test run > Results analysis > Query review > Final decision > Pay > Closed_
