### ISSUE TITLE
[Go]: fasthttp model for XSS, SSRF, open redirect

### ISSUE THREAD

**Issue by am0o0** [github/securitylab#786]
### Query PR

https://github.com/github/codeql/pull/14123

### Language

GoLang

### CVE(s) ID list

- https://github.com/dapr/dapr/security/advisories/GHSA-59m6-82qm-vqgj usage of `ctx.Request.URI().FullURI()` and `ctx.Request.Header.Peek()`

### Report

I added SSRF sinks , user controlled remote sources, XSS sinks, open redirect sinks and some additional steps and sanitizers from fasthttp package.

### Are you planning to discuss this vulnerability submission publicly? (Blog Post, social networks, etc).

- [X] Yes
- [ ] No

**Comment by jorgectf** [comment]
👋 @amammad 

Thank you for your contribution. Unfortunately, we can't accept the submission as is taking into account the CodeQL code quality (lack of comments, not using the reference to `this` and so making the code difficult to read), and the low research done around the framework (wrong assumptions such as `DoRedirects` for `Http::Redirect`, which instead executes the request following redirects). 

An improvement of the submission may have a lot of potential, let us know if you would like to work on it to keep the submission open, otherwise I will close it as rejected.

**Comment by jorgectf** [comment]
@amammad very nice improvements! Thank you!

**Comment by ghsecuritylab** [comment]
Your submission is now in status **Query review**.

_For information, the evaluation workflow is the following:
Initial triage > Test run > Results analysis > Query review > Final decision > Pay > Closed_

**Comment by ghsecuritylab** [comment]
Your submission is now in status **Final decision**.

_For information, the evaluation workflow is the following:
Initial triage > Test run > Results analysis > Query review > Final decision > Pay > Closed_

**Comment by xcorail** [comment]
Created Hackerone report 2335428 for bounty 546296 : [786] [Go]: fasthttp model for XSS, SSRF, open redirect

**Comment by ghsecuritylab** [comment]
Your submission is now in status **Closed**.

_For information, the evaluation workflow is the following:
Initial triage > Test run > Results analysis > Query review > Final decision > Pay > Closed_
