### ISSUE TITLE
CodeQL query to detect SSRF in Python

### ISSUE THREAD

**Issue by JordyZomer** [github/securitylab#81]
## CVE ID(s)

There's no CVE for this.

## Report

* I created a query to identify Server Side Request Forgery vulnerabilities in Python, currently my query supports the following libraries: requests, urllib, urllib2, httplib. The query uses taint-tracking to track the inputs from HTTP requests to the taint source request hosts. *

You can see the query here: https://github.com/github/codeql/pull/3455

- [x] Are you planning to discuss this vulnerability submission publicly? (Blog Post, social networks, etc). *We would love to have you spread the word about the good work you are doing*
 Yes, on twitter :)

**Comment by xcorail** [comment]
👋🏾 @JordyZomer 

Our internal team has been working on a similar query for a while, which has been public on the CodeQL repo since late February in this [PR](https://github.com/github/codeql/pull/2933). While this work has been delayed and is not completed, it's still in a more advanced shape than your PR and makes it redundant.

We'd like however to thank you for your contribution with a reward 🎉 
`Created Hackerone report 872094 for bounty 216649 : [81] CodeQL query to detect SSRF in Python`

Looking forward to your next contributions!
