### ISSUE TITLE
CSHARP: Experimental query for tainted WebClient

### ISSUE THREAD

**Issue by h3ku** [github/securitylab#89]
## CVE ID(s)

No CVE.
I found an instance of this issue in a private code repository, this code pattern is mentioned also in the following presentation https://youtu.be/E5_S_Yip3gc?t=559

## Report

The WebClient class provides a variety of methods for data transmission and communication with a particular URI. Despite of the class' naming convention, the URI scheme can also identify local resources, not only remote ones. Tainted by user-supplied input, the URI can be leveraged to access resources available on the local file system, therefore leading to the disclosure of sensitive information. This can be trivially achieved by supplying path traversal sequences (../) followed by an existing directory or file path.

Sanitization of  user-supplied URI values using the StartsWith("https://")</code> method is deemed insufficient in preventing arbitrary file reads. This is due to the fact that .NET ignores the protocol handler (https in this case) in URIs like the following: "https://../../../../etc/passwd". 

I think that the query is specially interesting since this a "mistake" that a developer can easily make unless he deeply know the internals of the function and .net. 

The query has already being merged into the official repo https://github.com/github/codeql/pull/3486

- [x] Are you planning to discuss this vulnerability submission publicly? (Blog Post, social networks, etc). *We would love to have you spread the word about the good work you are doing*

**Comment by xcorail** [comment]
Thanks for the submission! We have reviewed your report and validated your findings. After internally assessing the findings and the query we have determined this query is not giving any result on a real life project, and is therefore not eligible for a reward under the Bug Bounty program.

Even though this issue was assessed as being ineligible, we appreciate you bringing it to our attention. Your PR is merged it into the experimental folder, and we would still like to offer you $250.

Best regards and happy hacking!
